# Section 1 : Load in numpy (remember to pip install numpy first)

In [1]:
import numpy as np

# Section 2 : The Basics

In [ ]:
a = np.array([1, 2, 3])
a # same as print(a)

[1 2 3]


In [5]:
# 2d array
b = np.array([[9.0, 8.0, 7.0],[6.0,5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get dimension
a.ndim # number of dimensions

1

In [9]:
b.ndim

2

In [10]:
# Get Shape
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [12]:
# Get Type
a.dtype

dtype('int64')

In [13]:
# Get Size
a.itemsize

8

In [ ]:
# Get total elements
a.size

3

In [16]:
# Get total size
#a.size * a.itemsize
a.nbytes

24

In [18]:
b.itemsize

8

In [17]:
b.size

6

# Section 3 : Accessing/changing specific elements, rows, columns, etc

In [19]:
c = np.array([[1, 2, 3, 4, 5, 6, 7],[8, 9, 10, 11, 12, 13, 14]])
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
c.shape

(2, 7)

In [22]:
# Get a specific element [r, c]
c[1,5]

np.int64(13)

In [23]:
# Get a specific row
c[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
# Get a specific column
c[:, 2]

array([ 3, 10])

In [25]:
# Getting a little more fancy [startindex : endindex : stepsize]
c[0, 1:-1:2]

array([2, 4, 6])

In [26]:
c[1, 5] = 20
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [27]:
c[:, 2] = 5
print(c)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [28]:
c[:, 2] = [1, 2]
print(c)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# Section 4 : 3d example

In [32]:
d = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Get specific element(work outside in)

In [34]:
d[0, 1, 1]

np.int64(4)

In [35]:
d[:, 1, :]

array([[3, 4],
       [7, 8]])

In [36]:
d[:, 0, :]

array([[1, 2],
       [5, 6]])

In [37]:
d[:, 0, 0]

array([1, 5])

In [39]:
# replace
d[:, 1, :] = [[9, 9], [8, 8]]
d

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Section 5 : Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [41]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [43]:
# All 1s matrix
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [44]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [47]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [46]:
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [48]:
# Any other number (full_like)
np.full_like(d.shape, 4)

array([4, 4, 4])

In [49]:
np.full_like(d, 4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [50]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.37122398, 0.03078478],
       [0.81585381, 0.91580839],
       [0.70488812, 0.79265006],
       [0.79228608, 0.77601225]])

In [51]:
np.random.rand(4, 2, 3)

array([[[0.01029564, 0.83837064, 0.96013432],
        [0.93187968, 0.80376515, 0.57980306]],

       [[0.35893623, 0.81883177, 0.22531239],
        [0.3878096 , 0.71538359, 0.87639842]],

       [[0.08137528, 0.28584265, 0.85781148],
        [0.40029128, 0.65090356, 0.83547443]],

       [[0.280768  , 0.6790453 , 0.04889492],
        [0.92814256, 0.96074222, 0.92272551]]])

In [52]:
# Random decimal numbers
np.random.random_sample(d.shape)

array([[[0.22912842, 0.06400179],
        [0.74666075, 0.8613532 ]],

       [[0.8349935 , 0.8253828 ],
        [0.58861106, 0.80120503]]])

In [53]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.29262094, 0.54909606],
       [0.37034402, 0.49572803],
       [0.35682716, 0.89973485],
       [0.61654993, 0.68497139]])

In [55]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[4, 0, 6],
       [1, 4, 5],
       [0, 4, 0]], dtype=int32)

In [57]:
np.random.randint(4, 7, size=(3,3))

array([[4, 6, 6],
       [6, 5, 6],
       [4, 6, 6]], dtype=int32)

In [58]:
np.random.randint(-4, 7, size=(3,3))

array([[ 1,  3,  0],
       [-4,  1, -1],
       [ 6,  3,  3]], dtype=int32)

In [ ]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [67]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [69]:
z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [70]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Section 6 : Be careful when copying arrays!!!

In [73]:
a = np.array([1, 2, 3])
b = a.copy()
#b[0] = 100

print(b)

[1 2 3]


In [74]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


# Section 7 : Mathematics

In [75]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [76]:
a + 2

array([3, 4, 5, 6])

In [77]:
a - 2

array([-1,  0,  1,  2])

In [78]:
a * 2

array([2, 4, 6, 8])

In [79]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [80]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [81]:
a ** 2

array([ 1,  4,  9, 16])

In [83]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [84]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Section 8 : Linear Algebra

In [88]:
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [89]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Section 9 : Statistics

In [90]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
np.min(stats)

np.int64(1)

In [92]:
np.max(stats)

np.int64(6)

In [93]:
np.min(stats, axis=1)

array([1, 4])

In [94]:
np.min(stats, axis=0)

array([1, 2, 3])

In [96]:
np.max(stats, axis=1)

array([3, 6])

In [98]:
np.max(stats, axis=0)

array([4, 5, 6])

In [99]:
np.sum(stats)

np.int64(21)

# Section 10 : Reorganizing Arrays

In [100]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [101]:
print(before.shape)

(2, 4)


In [102]:
after = before.reshape((8, 1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [103]:
after = before.reshape((4, 2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [104]:
after = before.reshape((2, 2, 2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [106]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
# Horizontal stack
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Section 11 : Miscellaneous

In [110]:
# Load Data from file

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [112]:
filedata.astype('int32')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [113]:
# Boolean Masking and Advanced Indexing
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [114]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [115]:
# You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [116]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [118]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [121]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [122]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])