# Section 1 : Inverse matrix to solve a system

In [5]:
import numpy as np
from sympy import *

# Use arrays instead of matrices
a1 = np.array([[14, 0, 11], [22, 23, 4], [-12, -34, -3]])
a2 = np.array([[3], [7], [-4]])

mInv = np.linalg.inv(a1)
mDotA = np.around(np.dot(mInv, a1))
mDot = np.dot(mInv, a2)
print(mDot)

print("\n compare : ")
print(445/1358)
print(10/679)
print(-14/97)

print(mDotA)

[[ 0.33027739]
 [ 0.01410437]
 [-0.14762576]]

 compare : 
0.3276877761413844
0.014727540500736377
-0.14432989690721648
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Section 2 : Another inverse matrix system example

In [7]:
import numpy as np
from sympy import *

# points
x1 = -2
y1 = 0
x2 = -3
y2 = 0
x3 = -2.5
y3 = -.25

# rref method
M = Matrix([[x1**2, x1, 1, y1], [x2**2, x2, 1, y2], [x3**2, x3, 1, y3]])
m_rref = M.rref()

# Answers
a = round(m_rref[0][3])
b = round(m_rref[0][7])
c = round(m_rref[0][11])
print("a = ", a)
print("b = ", b)
print("c = ", c)

# Inverse matrix method
arr3x3 = np.array([[x1**2, x1, 1], [x2**2, x2, 1], [x3**2, x3, 1]])
arr3x1 = np.array(([y1], [y2], [y3]))
arrInv = np.linalg.inv(arr3x3)
identity = np.around(np.dot(arrInv,arr3x3))
arrValues = np.dot(arrInv, arr3x1)
print(identity)
print("Answers")
print(arrValues)
print("a = ", round(arrValues.item(0)))
print("b = ", round(arrValues.item(1)))
print("c = ", round(arrValues.item(2)))

a =  1
b =  5
c =  6
[[ 1.  0. -0.]
 [-0.  1. -0.]
 [-0.  0.  1.]]
Answers
[[1.]
 [5.]
 [6.]]
a =  1
b =  5
c =  6


# Section 3 : Transformations

In [11]:
import numpy as np

points = np.matrix(([1, 2], [3, 6], [3, 9]))
print(points.item(0, 1))
print(points)
tPoints = np.transpose(points)
print("\n transposed : ")
print(tPoints)
print("\n transposed back : ")
originalPoints = np.transpose(tPoints)
print(originalPoints)
print("\n as an array : ")
arr = np.array(points)
print(arr.item(2,1))
x = []
y = []
x.append(arr.item(0, 0))
y.append(arr.item(0, 1))
print(x, "," ,y)

2
[[1 2]
 [3 6]
 [3 9]]

 transposed : 
[[1 3 3]
 [2 6 9]]

 transposed back : 
[[1 2]
 [3 6]
 [3 9]]

 as an array : 
9
[1] , [2]
