# Section 1 : 

Matrix A : [a11 a12
            a21 a22]

Matrix B : [b11 b12
            b21 b22]

In [ ]:
# enter all values
a11 = 1
a12 = 2
a21 = 3
a22 = 4

b11 = 5
b12 = 6
b21 = 7
b22 = 8

# Section 2 : [A] + [B] = [C]

for addition and subtraction equal dimensions are necessary

In [1]:
a11 = 1
a12 = 2
a21 = 3
a22 = 4

b11 = 5
b12 = 6
b21 = 7
b22 = 8

c11 = a11 + b11
c12 = a12 + b12
c21 = a21 + b21
c22 = a22 + b22

print(c11,c12)
print(c21, c22)

6 8
10 12


# Section 3 : [A] x [B] = [C]

A = 2 x 2
B = 2 x 3

column of matrix A and row of matrix B should be same
The result is matrix C that is 2 x 3 

In [1]:
# 2 x 2

import numpy as np
# enter all values
a11 = 1
a12 = 2
a21 = 3
a22 = 4

b11 = 5
b12 = 6
b21 = 7
b22 = 8

# The actual steps
c11 = a11*b11 + a12*b21
c12 = a11*b12 + a12*b22
c21 = a21*b11 + a22*b21
c22 = a21*b12 + a22*b22

print("Multiplying Matrix A * Matrix B")
print(c11, c12)
print(c21, b22)

# numpy
print("\n same matrix : ")
A = np.array([[a11, a12], [a21, a22]])
B = np.array([[b11, b12], [b21, b22]])
C = A.dot(B)
print(C)

# np.matrix
print("\n np.matrix")
E = np.matrix([[a11, a12], [a21, a22]])
F = np.matrix([[b11, b12], [b21, b22]])
G = E.dot(F)
print(G)

Multiplying Matrix A * Matrix B
19 22
43 8

 same matrix : 
[[19 22]
 [43 50]]

 np.matrix
[[19 22]
 [43 50]]


# Section 4 : Other matrix operations

In [ ]:
import numpy as np
# enter all values
a11 = 1
a12 = 2
a21 = 3
a22 = 4

A = np.matrix([[a11, a12], [a21, a22]])
print("Matrix A : ")
print(A)

# more about Matrix A
print("\n inverse of Matrix A :")
print(np.linalg.inv(A)) # Line algebra

print("\n determinent of Matrix A : ")
print(np.round(np.linalg.det(A)))

print("\n Matrix A is multiplied by its inverse : ")
D = np.around(A.dot(np.linalg.inv(A)))
print(D)

# Multiplying a matrix by its inverse gives its identity matrix
[[1, 0]
 [0, 1]]


Matrix A : 
[[1 2]
 [3 4]]

 inverse of Matrix A :
[[-2.   1. ]
 [ 1.5 -0.5]]

 determinent of Matrix A : 
-2.0

 Matrix A is multiplied by its inverse : 
[[1. 0.]
 [0. 1.]]


# Section 5 : Another way to multiply two matrices

In [5]:
import numpy as np

# Matrices as matrix objects
c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print("\nc", type(c))
print(c)
print("\nd", type(d))
print(d)
print("\n dot product of two matrix objects")
print(np.dot(c, d))


c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]

 dot product of two matrix objects
[[21 24 27]
 [47 54 61]]
