# Section 1 : Reduced Row Echelon Form

14x + 11z = 3
22x + 25y + 4z = 7
-12x -34y -3z = -4

[[14, 0, 11, 3]
 [22, 25, 4, 3]
 [12, -34, 3, -4]]

[[1, 0, 0, __]
 [0, 1, 0, __]
 [0, 0, 1, __]]

In [5]:
# Converting Matrix and Array objects in Numpy

import numpy as np
from sympy import *

# Create an array
arr = np.array([[14, 0, 11, 3], [22, 25, 4, 7], [-12, -34, -3, -4]])

# Create a matrix from that array
M = Matrix(arr)
print("Matrix : {}".format(M))

# In some situations you would need to build an array but for matrix operations matrix is necessary

# convert that matrix back to an array
A = np.array(M)
print("\n same matrix : ")
print(A)

# Solve using rref in the matrix
print("\n answers : ")
M_rref = M.rref() # Reduced Row Echelon Form
x = M_rref[0][3]
y = M_rref[0][7]
z = M_rref[0][11]
print("x = ", x)
print("y = ", y)
print("z = ", z)

print("\n row echelon form of matrix : \n {}".format(M_rref))

Matrix : Matrix([[14, 0, 11, 3], [22, 25, 4, 7], [-12, -34, -3, -4]])

 same matrix : 
[[14 0 11 3]
 [22 25 4 7]
 [-12 -34 -3 -4]]

 answers : 
x =  445/1358
y =  10/679
z =  -14/97

 row echelon form of matrix : 
 (Matrix([
[1, 0, 0, 445/1358],
[0, 1, 0,   10/679],
[0, 0, 1,   -14/97]]), (0, 1, 2))
